### ISSUE TITLE
Install in windows giving version mismatch error.

### ISSUE THREAD

**Issue by pnunn** [eugenpt/lite-xl-vibe#15]
Hi,

Thanks for your work on this plugin.  Just new to lite-xl and am trying to install your plugin on a windblows box under data/plugins with a git clone, but when I start lite-xl its giving me a version error on your plugin (although as far as I can see, the init.lua has the same version as the other plugins directly in the plugins directory that seem to work.

Am I doing something wrong? 

Ta  Peter.

**Comment by eugenpt** [comment]
Well, it would help if you could provide 
- lite-xl version
- top lines from `lite-xl-vibe/init.lua`
- names and top lines from some other plugins
- in windows it's usually better to install plugins into `C:\Users\<user>\.config\lite-xl\plugins`

**Comment by pnunn** [comment]
OK, fair comment.
Version: not a clue, can't find it anywhere, but, downloaded today from releases an the win x86-64.zip file.

Header from vibe: -- mod-version:1 -- lite-xl 2.0
Header from minimap -- mod-version:2
Header from rainbowparen -- mod-version:2 -- lite-xl 2.0

I tried moving the lite-xl-vibe folder to .config\lite-xl\plugins. Exactly the same error.


Error Message: Some plugins are not loaded due to version mismatch.

Plugins from directory "-\Documents\lite-xl\data":lite-xl-vibe.

Please download a recent version from https://github.com/franko/lite-plugins.

**Comment by eugenpt** [comment]
Oh, yeah, as you can see version is wrong ) wait a sec, I did not see the 2.01 version)

**Comment by eugenpt** [comment]
Now?

**Comment by pnunn** [comment]
That fixed it :)

All good.  Thanks.

**Comment by eugenpt** [comment]
Thanks for the issue!
