### ISSUE TITLE
No mouse visual selection/zoom

### ISSUE THREAD

**Issue by M1ndo** [eugenpt/lite-xl-vibe#26]
The recent update either intentionally disabled mouse mode or it is broken.
i can't either do visual selection nor zooming in/out with mouse wheel.
PS: It would be great if you add "mark text using block mode with 'ctrl+v' in normal mode" as it is missing. 
Also: Suggestion on Keystroke are disabled or broken as well.

**Comment by eugenpt** [comment]
yeah, all mouse events are screwed for as long as I can not f(i/u)nd the time..

**Comment by eugenpt** [comment]
hoorah! to the commands with arguments in 2.1 !

**Comment by eugenpt** [comment]
@M1ndo a bit late on the answer, but hey! (insert sparta gif) this is vim emulation! what is this `mouse` you're talking about??)

visual block mode is non-existent, too much work imo - even visual line mode is not really here

**Comment by M1ndo** [comment]
> @M1ndo a bit late on the answer, but hey! (insert sparta gif) this is vim emulation! what is this `mouse` you're talking about??)
> 
> visual block mode is non-existent, too much work imo - even visual line mode is not really here

Mouse selection its like visual selection on insert/normal mode ( Mouse events whatever its named ) , ik visual block mode is not implemented yet (hopefully in the future), but yeah thanks for patching it.
